/*
** Copyright (c) 2006 Christopher Davis
** 
** Permission is hereby granted, free of charge, to any person obtaining a copy of
** this software and associated documentation files (the "Software"), to deal in 
** the Software without restriction, including without limitation the rights to 
** use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
** the Software, and to permit persons to whom the Software is furnished to do so,
** subject to the following conditions:
** 
** The above copyright notice and this permission notice shall be included in all 
** copies or substantial portions of the Software.
** 
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
** FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
** COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER 
** IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
** CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
** 
** $Id$
*/



//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: fragmon.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_fragmon_H__
#define __WDR_fragmon_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "fragmon_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_TEXT = 10000;
const int ID_IRC_SERV_IN = 10001;
const int ID_IRC_PASS_CHK = 10002;
const int ID_IRC_PASS_IN = 10003;
const int ID_IRC_USER_IN = 10004;
const int ID_IRC_REAL_IN = 10005;
const int ID_IRC_NICK1_IN = 10006;
const int ID_IRC_NICK2_IN = 10007;
const int ID_IRC_NICK3_IN = 10008;
wxSizer *IRCInputFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_SERV_QUERY = 10009;
const int ID_SERV_IN = 10010;
const int ID_SERV_PLAY = 10011;
const int ID_SERV_TYPE = 10012;
const int ID_SERV_COPY = 10013;
const int ID_SERV_SAVE = 10014;
const int ID_SERV_EDIT = 10015;
const int ID_DEL = 10016;
const int ID_SERV_LIST = 10017;
const int ID_LINE = 10018;
const int ID_PASSLOCK = 10019;
const int ID_SERV_HOST = 10020;
const int ID_SERV_PING = 10021;
const int ID_SERV_MAP = 10022;
const int ID_SERV_PLAYERS = 10023;
const int ID_SERV_GTYPE = 10024;
const int ID_SERV_MOD = 10025;
const int ID_SERV_VERS = 10026;
wxSizer *QueryInputFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_EXEC_TYPE = 10027;
const int ID_EXEC_PATH_IN = 10028;
const int ID_EXEC_GETPATH = 10029;
const int ID_EXEC_ORDER_IN = 10030;
const int ID_EXEC_CONN_IN = 10031;
const int ID_EXEC_PASS_IN = 10032;
const int ID_EXEC_NAME_IN = 10033;
const int ID_EXEC_EX = 10034;
wxSizer *ExecInputFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_CFMT_IN = 10035;
const int ID_CFMT_EX = 10036;
wxSizer *CopyFmtFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_DEF_GM = 10037;
const int ID_QUERY_TO = 10038;
wxSizer *QueryOptsFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_COMP_NAME_A = 10039;
const int ID_STATICBITMAP = 10040;
const int ID_COMP_NAME_B = 10041;
const int ID_COMP_SCORE_A = 10042;
const int ID_COMP_SCORE_B = 10043;
const int ID_COMP_TIME = 10044;
wxSizer *CompOutputFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_SBS_STATUS_OUT = 10045;
const int ID_SBS_SERV_IN = 10046;
const int ID_SBS_TITLE_IN = 10047;
const int ID_SBS_CHAN_IN = 10048;
const int ID_SBS_CHAN = 10049;
const int ID_SBS_INTER_IN = 10050;
const int ID_SBS_CUST_CHK = 10051;
const int ID_SBS_BNAME_IN = 10052;
const int ID_SBS_OPTS_LST = 10053;
wxSizer *ScorebotInputFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_BOT_FORMAT_IN = 10054;
const int ID_BOT_EX_OUT = 10055;
wxSizer *BroadcastFmtFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_CI_IN = 10056;
const int ID_CI_JOIN = 10057;
const int ID_CI_LIST = 10058;
const int ID_CI_PART = 10059;
wxSizer *ChannelInputFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

const int ID_MENU = 10060;
const int ID_SET_NAME = 10061;
const int ID_QUERY_DBG = 10062;
const int ID_QUERY_RLD = 10063;
const int ID_OPTIONS = 10064;
const int ID_IRC_NICK = 10065;
const int ID_IRC_CHAN = 10066;
const int ID_IRC_BC = 10067;
const int ID_IRC_BC_CONF = 10068;
const int ID_IRC_BC_START = 10069;
const int ID_IRC_BC_STOP = 10070;
const int ID_IRC_BC_PULSE = 10071;
const int ID_IRC_BC_PP = 10072;
const int ID_HELP = 10073;
wxMenuBar *MenuFunc();

// Declare toolbar functions

// Declare bitmap functions

wxBitmap ArrowsFunc( size_t index );

const int ID_MINIDOWN = 10074;
const int ID_MINIUP = 10075;
wxBitmap SortArrowsFunc( size_t index );

const int ID_TEAM_A = 10076;
const int ID_TEAM_B = 10077;
const int ID_TEAM_F = 10078;
wxBitmap TeamsFunc( size_t index );

const int ID_LOCK_ON = 10079;
const int ID_LOCK_OFF = 10080;
wxBitmap LocksFunc( size_t index );

#endif

// End of generated file
